
productService:
  replicaCount: 1
  image: ghcr.io/danilond/product-service-ecommerce-boot:latest
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  configImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC
  hpa:
    minReplicas: 1
    maxReplicas: 5
  imagePullSecrets:
    - name: ghcr-secret

orderService:
  replicaCount: 1
  image: ghcr.io/danilond/order-service-ecommerce-boot:latest
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC
  imagePullSecrets:
    - name: ghcr-secret

paymentService:
  replicaCount: 1
  image: ghcr.io/danilond/payment-service-ecommerce-boot:latest
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC
  imagePullSecrets:
    - name: ghcr-secret

shippingService:
  replicaCount: 1
  image: ghcr.io/danilond/shipping-service-ecommerce-boot:latest
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC
  imagePullSecrets:
    - name: ghcr-secret

favouriteService:
  replicaCount: 1
  image: ghcr.io/danilond/favourite-service-ecommerce-boot:latest
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC
  imagePullSecrets:
    - name: ghcr-secret

proxyClient:
  replicaCount: 1
  image: ghcr.io/danilond/proxy-client-ecommerce-boot:latest
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC
  imagePullSecrets:
    - name: ghcr-secret

apiGateway:
  replicaCount: 1
  image: ghcr.io/danilond/api-gateway-ecommerce-boot:latest
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms512m -Xmx1Gi -XX:+UseG1GC
  imagePullSecrets:
    - name: ghcr-secret
namespace: production

serviceDiscovery:
  replicaCount: 2
  image: ghcr.io/danilond/service-discovery-ecommerce-boot:latest
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  configImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms512m -Xmx1Gi -XX:+UseG1GC
# HPA
  hpa:
    minReplicas: 2
    maxReplicas: 5
  imagePullSecrets:
    - name: ghcr-secret

userService:
  replicaCount: 1
  image: ghcr.io/danilond/user-service-ecommerce-boot:latest
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  configImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC
  hpa:
    minReplicas: 1
    maxReplicas: 8
  imagePullSecrets:
    - name: ghcr-secret

zipkin:
  replicaCount: 1
  image: openzipkin/zipkin:latest

cloudConfig:
  replicaCount: 2
  image: ghcr.io/danilond/cloud-config-ecommerce-boot:latest
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC
  imagePullSecrets:
    - name: ghcr-secret

orderService:
  replicaCount: 1
  image: ecommerceacr1202.azurecr.io/order-service:0.1.0
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC

paymentService:
  replicaCount: 1
  image: ecommerceacr1202.azurecr.io/payment-service:0.1.0
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC

shippingService:
  replicaCount: 1
  image: ecommerceacr1202.azurecr.io/shipping-service:0.1.0
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC

favouriteService:
  replicaCount: 1
  image: ecommerceacr1202.azurecr.io/favourite-service:0.1.0
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC

proxyClient:
  replicaCount: 1
  image: ecommerceacr1202.azurecr.io/proxy-client:0.1.0
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms256m -Xmx512m -XX:+UseG1GC

apiGateway:
  replicaCount: 1
  image: ecommerceacr1202.azurecr.io/api-gateway:0.1.0
  springProfile: prod
  zipkinUrl: http://zipkin:9411
  eurekaMyZone: http://service-discovery:8761/eureka
  eurekaDefaultZone: http://service-discovery:8761/eureka/
  springConfigImport: optional:configserver:http://cloud-config:9296/
  javaOpts: -Xms512m -Xmx1Gi -XX:+UseG1GC
